name: test

on:
  push:
  pull_request:
    types: [opened, reopened, review_requested, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dirs:
          - "01-ec2"
          - "02-state"
          - "04-module"
          - "05"
    defaults:
      run:
        working-directory: ${{ matrix.dirs }}
    steps:
      - uses: hashicorp/setup-terraform@v3
      - uses: actions/checkout@v4

      - name: init
        run: terraform init

      - name: format check
        run: terraform fmt -check -recursive

      - name: validate
        run: terraform validate
